from decouple import config

DISCORD_TOKEN = config("DISCORD_TOKEN")
DISCORD_SERVER_ID = config("DISCORD_SERVER_ID")
EVENTBRITE_EVENT_ID = config("EVENTBRITE_EVENT_ID")
EVENTBRITE_API_TOKEN = config("EVENTBRITE_API_TOKEN")
AUTH_INDEX_PATH = config("AUTH_INDEX_PATH")
AUTH_INDEX_CACHED = config("AUTH_INDEX_CACHED")
AUTH_ATTENDEE_ROLE = config("AUTH_ATTENDEE_ROLE")
PYBR_WELCOME_CHANNEL = config("PYBR_WELCOME_CHANNEL")
